### ISSUE TITLE
import 가 이상한데, 일부러 이렇게 해 놓으신건가요?

### ISSUE THREAD

**Issue by devkan** [teddylee777/langchain-kr#1]
안녕하세요. 저번에 contributor 한다고 했던 Kan이라고 합니다.. 칸이라고 해 주세용.. ㅎㅎ
fork해서 로컬에서 어떤 것을 해 볼까 하고 기존 문서를 보다가 궁금한 것이 생겨서 질문 드립니다..
문서가 다들 초기 버전으로 구성이 되어 있더군요..

기존 파일
```python
from langchain_openai import ChatOpenAI
from langchain_core.output_parsers import StrOutputParser
```

현재 버전 import
```
from langchain.chat_models import ChatOpenAI
from langchain.output_parsers import StructuredOutputParser
```

이처럼 패키지명 예전것으로 되어 있는데, 이 참에 다 버전업을 시켜 볼까 하는데.. 어떤지 하고요.. ㅎㅎ

혹 부족하거나 채웠으면 하는게 있으면 2~3개만 알려주세요.
가능하면 그쪽으로 한번 해 보려고요..
그럼 답변 주세용.. ^^;

**Comment by teddylee777** [comment]
칸님 안녕하세요^^

버전 import 최신으로 업데이트 해주시는 것 너무 감사드립니다. 꼭 필요한 작업입니다!

그런데 참고로 최신 버전이 아래 코드입니다.

```python
from langchain_openai import ChatOpenAI
from langchain_core.output_parsers import StrOutputParser
```

반대로 말씀하신 것 같아서 미리 말씀 드립니다.
아래 코드는 legacy 코드라 앞으로 지원이 종료될 예정인 코드입니다.

import 최신으로 업데이트 하여 기여해 주시면 메인에 병합하도록 하겠습니다!

너무너무 감사합니닷!!

**Comment by devkan** [comment]
다시 체크해 보니, 제가 잘못 알고 있었네요.. 으미~ 민망한것..
제가 설치한 것이 0.0.332 이였네요.. 지금끼지 대충봐서 0.3 버전이라고 생각하고 있었거든요..
그래서 fork해 오고, langchain 새로이 설치해서 버전 확인 했음에도 0.1.16 이 하위 버전이라고 생각하게 되었네요..
그 얼마나 되었다고 전 아직도 langchain하고 . 을 바로 찍게 되네요..

이 문서를 보신 분들은 새로이 langchain을 설치하니, 다들 0.1.16 버전 이상이라고 생각은 됩니다.
하지만, 현재 구글 되는 문서나 gpt 답변들은 거의 이전 패키지 형태의 코드들이 많은거 같습니다.
그래서 문서에 이를 표기해 두는 것이 어떤가 싶습니다.

그렇게 1.1 챕터부터 하나씩 부연설명 기재해 나가면서, 새롭게 추가되거나 기능 향상된 것들이 뭔가 있는지 확인해 보려고 합니다.
그러면서 저도 업그레이드도 시키고요..
쓸따리 없는 짓이 아닌가 싶어 우선 적어보고요..
샘플용으로 몇개 수정후 merge 요청하겠습니다.. ^^;
