### ISSUE TITLE
예제 소스 오류: CH02 프롬프트, 02 퓨샷프롬프트

### ISSUE THREAD

**Issue by stsr1284** [teddylee777/langchain-kr#13]
"Example Selector 의 유사도 검색 문제 해결" 부분에서

https://github.com/teddylee777/langchain-kr/blob/218aba0c48312ea54d72a97617ebe2ae58679e78/02-Prompt/02-FewShotTemplates.ipynb#L535

에서 'few_shot_prompt'가 아닌 'custom_fewshot_prompt'가 들어가야하는거 아닌가요??

**Comment by teddylee777** [comment]
@stsr1284 님 오류 제보 감사합니다. 
오류 수정하여 업데이트 하였습니다!

감사합니다.
