### ISSUE TITLE
Modelfile 구문 오류

### ISSUE THREAD

**Issue by corean** [teddylee777/langchain-kr#2]
ollama 등록하는중에 오류가 있습니다.

https://github.com/teddylee777/langserve_ollama/blob/main/ollama-modelfile/EEVE-Korean-Instruct-10.8B-v1.0/Modelfile 

```bash
ollama create EEVE-Korean-10.8B -f EEVE-Korean-Instruct-10.8B-v1.0-GGUF/Modelfile
transferring model data
creating model layer
creating template layer
creating system layer
creating parameters layer
Error: unknown parameter 'TEMPERATURE'
```
오류나는 부분:
PARAMETER TEMPERATURE 0 

소문자로 변경하니 오류없이 등록됩니다.
PARAMETER temperature 0

**Comment by corean** [comment]
잘못된 저장소에 올렸네요. 죄송합니다.

**Comment by teddylee777** [comment]
감사합니다. 해당 Repository 에 업데이트 하도록 하겠습니다^^
