### ISSUE TITLE
11-Retriever/10-Kiwi-BM25Retriever.ipynb 문의

### ISSUE THREAD

**Issue by inkyungil** [teddylee777/langchain-kr#3]
안녕하세요 테디님 유튜브 영상 잘 보고 있습니다.
다름이 아니라 최근 업로드 하신 내용을 실습 하다 잘 안되는 부분이 있어 문의하게되었습니다.
11-Retriever/10-Kiwi-BM25Retriever.ipynb에서 성능 테스트를 해주셨는데요! 
궁금한 부분이 사용자의 질문에 따라 답변을 찾아주는데 Similarity를 표시하면 더 좋을거 같아 구현을 열심히 해봤는데.. 잘안되네요. 혹시 팁있으시면 공유 부탁합니다. 
감사합니다.

**Comment by teddylee777** [comment]
@inkyungil 님 제가 답변이 늦었습니다 ㅠ

이번 업데이트때 스코어 계산 로직을 추가 하였습니다^^

11-Retriever/11 번 Korean Tutorial 파일을 참고해 주세요!

의견 감사합니다!
