### ISSUE TITLE
#llama3 로 #agent 🤖 만드는 방법 + 8B 오픈 모델로 Agent 구성하는 방법

### ISSUE THREAD

**Issue by JuhanKimSeoul** [teddylee777/langchain-kr#6]
title에 적은 유튜브 방송 보고 깃 클론 받아서 실행하였는데, 

EEVE Korean (LM Studio) 주피터 실행도중 아래와 같이 ApiConnection error가 발생하였습니다. 

주피터 노트북에 보니 "동작 X" 라고 하셨는데, 이거 지금은 안되는 건가요??
<img width="1263" alt="error" src="https://github.com/teddylee777/langchain-kr/assets/128209402/d4b61025-27dc-43ad-ba2e-48de637fa6e6">

**Comment by teddylee777** [comment]
네, 해당 코드는 동작하지 않습니다.
이유에 대해서는 유튜브 영상에서 말씀드렸으며, 대안과 해결하는 코드도 영상에 포함되어 있으니 한 번 확인해 보시면 좋을 것 같습니다.
감사합니다.
